### ISSUE TITLE
cannot deploy application using poetry

### ISSUE THREAD

**Issue by setswei** [codesmith-gmbh/forge-cogcf-barrier#1]
Currently trying to follow your tutorial and which i run the command poetry `run -- deploy -f test-assembly.yaml  ` if get the error below.
```

[FileNotFoundError]
[Errno 2] No such file or directory
```
Not entirely sure why this is happening and all the fixes around this error and poetry are not working. have you run into this issue before ?

**Comment by blakeaw6** [comment]
Hi, I am having this same issue. Did you find a solution for it? @setswei

**Comment by stanislas** [comment]
Hi guys,

@setswei sorry for the late answer and thank you for reporting the error.

This is due to the flag separator `--` that was necessary in beta versions of poetry.
If you have a recent version of poetry (1.0.5), you can do the following (without the `--`):

```
poetry install # to install the dependencies
poetry run deploy -f test-assembly.yaml # to deploy
```

I also noticed an error in the template for the configuration file (in the blog post). Please use the following (no `https://` prefix for CognitoUserPool.DomainName):
```yaml
StacksPrefix: TestBarrier
CookieName: TestBarrier
Environment:
  AWSProfile: <<<profile-name>>>
  Region: us-east-1
Packaging:
  S3Buckets:
    us-east-1: <<<S3 bucket name>>>
  S3Prefix: TestBarrier
Cloudfront:
  DomainName: <<<cloudfront domain name>>>
CognitoUserPool:
  UserPoolId: <<<user pool id>>>
  DomainName: <<<user pool domain prefix>>>.auth.us-east-1.amazoncognito.com
  UserPoolClientProperties:
    ReadAttributes:
      - email
    WriteAttributes:
      - email
    SupportedIdentityProviders:
      - COGNITO
```
